version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/:/var/www/html/
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - 8000:80
        environment:
            UPLOAD_LIMIT: 64M
    db:
        container_name: db
        image: mysql
        restart: always
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: projeto
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 64M
        depends_on:
            - db